"""add book author relation and user roles

Revision ID: 543e33d17731
Revises: 8e37c01b8903
Create Date: 2026-08-24 16:53:58.491193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543e33d17731'
down_revision: Union[str, Sequence[str], None] = '8e37c01b8903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_books_author_id'), 'books', ['author_id'], unique=False)
    op.create_foreign_key(None, 'books', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'author')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('user', 'author', 'admin', name='user_role', native_enum=False, create_constraint=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'author', 'admin', name='user_role', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.add_column('books', sa.Column('author', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_author_id'), table_name='books')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
