"""add soft delete fields to books

Revision ID: 9fbce112ed5e
Revises: 543e33d17731
Create Date: 2026-08-25 13:32:23.905544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbce112ed5e'
down_revision: Union[str, Sequence[str], None] = '543e33d17731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'books', 
        sa.Column(
            'is_deleted', 
            sa.Boolean(), 
            server_default=sa.text('0'), 
            nullable=False))
    op.add_column('books', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'deleted_at')
    op.drop_column('books', 'is_deleted')
    # ### end Alembic commands ###
